name: vframe_search
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - intel-openmp=2019.4=233
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.1=h0a44026_1
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1f=h1de35cc_0
  - pandas=1.0.3=py37h6c726b0_0
  - pip=19.1.1=py37_0
  - python=3.7.3=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - aioredis==1.2.0
    - alembic==1.2.1
    - amqp==2.5.0
    - annoy==1.16.0
    - async-timeout==3.0.1
    - billiard==3.6.0.0
    - celery==4.3.0
    - chardet==3.0.4
    - click==7.0
    - colorlog==4.0.2
    - cycler==0.10.0
    - dacite==1.0.2
    - decorator==4.4.0
    - dnspython==1.16.0
    - eventlet==0.25.0
    - flask==1.1.1
    - flask-classful==0.14.2
    - flask-socketio==4.2.1
    - flask-sqlalchemy==2.4.0
    - flask-wtf==0.14.2
    - greenlet==0.4.15
    - h5py==2.10.0
    - hiredis==1.0.0
    - idna==2.8
    - imagehash==4.0
    - imageio==2.5.0
    - imutils==0.5.2
    - infinity==1.4
    - intervals==0.8.1
    - itsdangerous==1.1.0
    - jinja2==2.10.1
    - joblib==0.13.2
    - kiwisolver==1.1.0
    - kombu==4.6.3
    - mako==1.1.0
    - markdown==3.1.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - monotonic==1.5
    - mysql-connector==2.2.9
    - networkx==2.3
    - numpy==1.17.0
    - opencv-python==4.1.0.25
    - pbr==5.4.3
    - pdoc==0.3.2
    - pdfkit==0.6.1
    - pillow==6.1.0
    - pymediainfo==4.0
    - pyparsing==2.4.2
    - python-dateutil==2.8.0
    - python-dotenv==0.10.3
    - python-editor==1.0.4
    - python-engineio==3.9.3
    - python-socketio==4.3.1
    - pytz==2019.2
    - pywavelets==1.0.3
    - pyyaml==5.1.2
    - redis==3.3.8
    - requests==2.22.0
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.3.0
    - simplejson==3.16.0
    - six==1.12.0
    - sqlalchemy==1.3.6
    - sqlalchemy-utc==0.10.0
    - sqlalchemy-utils==0.34.1
    - sqlparse==0.3.0
    - tempita==0.5.2
    - tqdm==4.32.2
    - urllib3==1.25.3
    - validators==0.13.0
    - vine==1.3.0
    - websocket-client==0.56.0
    - werkzeug==0.15.5
    - wtforms==2.2.1
    - wtforms-alchemy==0.16.9
    - wtforms-components==0.10.4
prefix: /Users/user/miniconda3/envs/vframe_search

